# Generated by Django 3.2.4 on 2021-06-11 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='received_requests',
            field=models.ManyToManyField(blank=True, related_name='_core_contact_received_requests_+', to='core.Contact'),
        ),
        migrations.AddField(
            model_name='contact',
            name='sent_requests',
            field=models.ManyToManyField(blank=True, related_name='_core_contact_sent_requests_+', to='core.Contact'),
        ),
    ]
